# @package cebra
# A descriptive name for this configuration
name: offset1-model-mse

model_architecture: offset1-model-mse

# CEBRA-specific parameters
output_dim: 2  # will be adjusted to match the number of classes
max_iterations: 15000
conditional: 'discrete'
criterion: learnableeuclidean
num_workers: 2
pin_memory: true
persistent_workers: true
prefetch_factor: 2
# Nested parameters for the model
params:
  batch_size: 512
  learning_rate: 3e-4 # Higher learning rate
  temperature: 1.0
  distance: 'euclidean' # Different distance metric
  prior: 'uniform'
  verbose: True
