# @package cebra
# A descriptive name for this configuration
name: offset5-model

model_architecture: offset5-model

# CEBRA-specific parameters
output_dim: 2
max_iterations: 10000
conditional: 'discrete'
num_workers: 2
pin_memory: true
persistent_workers: true
prefetch_factor: 2
# Nested parameters for the model
params:
  batch_size: 512
  learning_rate: 3e-4 # Higher learning rate
  temperature: 1.0
  distance: 'cosine' # Different distance metric
  verbose: True
